#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# Upper case to set environment variable and minor case to read from stdin
ALLOWED_HOSTS = data.get('host')
agent.set_env('ALLOWED_HOSTS', ALLOWED_HOSTS)
# just before starting systemd unit
agent.dump_env()
